<?php
require_once '../includes/session_config.php';
require_once '../includes/config.php';
require_once '../includes/functions.php';
require_once '../includes/auth.php';
require_once '../includes/security.php';
requireAuth();
requireAdmin();
setSecurityHeaders();
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<?= csrfTokenMeta() ?><title>Database Restore - <?= htmlspecialchars(APP_SHORT_NAME) ?></title>
<?= google_fonts_tag('Inter:wght@400;500;600;700;800') ?><script src="<?= asset_url('lucide') ?>"></script>
<link rel="stylesheet" href="../assets/css/sidebar.css?v=20260929-groups">
<style>
:root{--ink:#172033;--muted:#64748b;--line:#e2e8f0;--bg:#f6f8fb;--primary:#6750a4;--good:#15803d;--warn:#a16207;--bad:#b91c1c}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,"Segoe UI",sans-serif}.content{padding:30px 36px;max-width:1750px}.hero{background:linear-gradient(135deg,#7c2d12,#1e1b4b);color:#fff;border-radius:16px;padding:28px 32px;margin-bottom:20px}.hero h1{margin:0 0 7px;font-size:27px;display:flex;align-items:center;gap:10px}.hero p{margin:0;opacity:.9;font-size:14px}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 1px 3px #0000000d}.notice{padding:14px;border-radius:9px;background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;font-size:13px;margin-bottom:16px;line-height:1.5}.form-grid{display:grid;grid-template-columns:1.5fr 1fr 1fr auto;gap:12px;align-items:end}.field label{display:block;font-size:12px;font-weight:800;color:#475569;margin-bottom:5px}.field input,.field select{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:8px;padding:10px;background:#fff;font:inherit;font-size:13px}.btn,td button{border:1px solid #cbd5e1;background:#fff;border-radius:8px;padding:8px 11px;font:inherit;font-size:12px;font-weight:700;cursor:pointer}.btn-primary{border:0;background:var(--primary);color:#fff}.btn-danger{color:var(--bad)}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:10px}table{width:100%;border-collapse:collapse;min-width:1450px}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;font-size:12px}th{background:#f8fafc;color:#475569;font-size:11px;text-transform:uppercase}.status{display:inline-flex;padding:4px 8px;border-radius:999px;background:#eef2f7;font-weight:800}.status.awaiting_approval,.status.rollback_awaiting_approval{background:#fffbeb;color:var(--warn)}.status.running,.status.backup_running,.status.approved,.status.rolling_back{background:#eff6ff;color:#1d4ed8}.status.completed,.status.rolled_back{background:#ecfdf3;color:var(--good)}.status.completed_with_errors{background:#fffbeb;color:var(--warn)}.status.failed,.status.cancelled{background:#fef2f2;color:var(--bad)}.small{font-size:11px;color:var(--muted)}.pagination{display:flex;justify-content:space-between;align-items:center;margin-top:14px}.logs{max-height:260px;overflow:auto;background:#0f172a;color:#dbeafe;border-radius:9px;padding:12px;font:12px Consolas,monospace;white-space:pre-wrap}.empty{padding:28px;text-align:center;color:var(--muted)}@media(max-width:1000px){.content{padding:20px}.form-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<?php require_once '../includes/sidebar_nav.php'; ?>
<main class="content">
<section class="hero"><h1><i data-lucide="database-zap"></i> Full Database Restore</h1><p>Verified preview first, pre-restore backup second, then two-person approval before replacing the live database.</p></section>
<section class="card">
<div class="notice"><strong>Destructive operation:</strong> this feature replaces the live database with the verified SQL dump. It must be done during Maintenance Mode. The system requires a verified preview, a fresh rollback backup, two different administrator approvals, and an audit trail. PDF recovery is a separate controlled phase.</div>
<form id="form"><div class="form-grid"><div class="field"><label for="preview">Completed database restore preview</label><select id="preview" required><option value="">Loading...</option></select></div><div class="field"><label for="root">Rollback backup root</label><select id="root" required><option value="">Loading...</option></select></div><div class="field"><label for="folder">Rollback backup folder</label><input id="folder" maxlength="80" required value="iSCAN-PreRestore-DB-<?= date('Y-m-d-His') ?>"></div><button class="btn btn-primary" id="start" type="submit">Prepare restore</button></div></form>
<p class="small" id="maintenance">Maintenance Mode: checking...</p>
</section>
<section class="card"><div class="table-wrap"><table><thead><tr><th>ID</th><th>Status</th><th>Preview</th><th>Pre-restore backup</th><th>Approvals</th><th>Tables</th><th>PDF findings</th><th>Created</th><th>Actions</th></tr></thead><tbody id="jobs"><tr><td colspan="9" class="empty">Loading...</td></tr></tbody></table></div><div class="pagination"><span class="small" id="summary">Loading...</span><span><button id="prev" disabled>Previous</button> <button id="next" disabled>Next</button></span></div></section>
<section class="card" id="detail" hidden><h2 style="margin-top:0" id="detail-title">Restore details</h2><p class="small" id="detail-summary"></p><div class="logs" id="logs"></div></section>
</main>
<script>
const api='../api/database_live_restore.php',csrf=document.querySelector('meta[name="csrf-token"]')?.content||'',preview=document.getElementById('preview'),root=document.getElementById('root'),jobs=document.getElementById('jobs'),summary=document.getElementById('summary');let page=1,maintenance=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
async function request(url,options){const response=await fetch(url,{credentials:'same-origin',...(options||{})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'Database restore request failed.');return data;}
async function loadSetup(){const data=await request(`${api}?action=locations`);maintenance=!!data.maintenance_mode;const m=document.getElementById('maintenance');m.textContent=`Maintenance Mode: ${maintenance?'ENABLED':'DISABLED — required before approval'}`;m.style.color=maintenance?'#15803d':'#b91c1c';root.innerHTML=(data.locations||[]).map(item=>`<option value="${esc(item.root)}">${esc(item.root)} — ${Number(item.free_gb||0).toLocaleString()} GB free — ${item.writable?'writable':'read-only'}</option>`).join('')||'<option value="">No approved roots available</option>';const eligible=await request(`${api}?action=eligible`);preview.innerHTML=(eligible.jobs||[]).map(item=>`<option value="${Number(item.id)}">Preview #${Number(item.id)} — ${Number(item.staging_table_count||0)} tables — ${Number(item.pdf_missing_count||0)} PDF missing</option>`).join('')||'<option value="">No eligible completed preview</option>';}
function approvalText(item){return`Restore ${Number(item.restore_stage1_count||0)}/1 + ${Number(item.restore_stage2_count||0)}/1<br>Rollback ${Number(item.rollback_stage1_count||0)}/1 + ${Number(item.rollback_stage2_count||0)}/1`}
function actions(item){let out=`<button data-detail="${Number(item.id)}">Details</button> <button data-sync="${Number(item.id)}">Sync</button>`;if(item.status==='awaiting_approval'){if(Number(item.restore_stage1_count||0)===0)out+=` <button data-approve="restore" data-stage="1" data-id="${Number(item.id)}">Restore Stage 1</button>`;else if(Number(item.restore_stage2_count||0)===0)out+=` <button data-approve="restore" data-stage="2" data-id="${Number(item.id)}">Restore Stage 2</button>`;}if(['completed','completed_with_errors','failed'].includes(item.status)){if(Number(item.rollback_stage1_count||0)===0)out+=` <button data-approve="rollback" data-stage="1" data-id="${Number(item.id)}">Rollback Stage 1</button>`;else if(Number(item.rollback_stage2_count||0)===0)out+=` <button data-approve="rollback" data-stage="2" data-id="${Number(item.id)}">Rollback Stage 2</button>`;}if(['backup_running','awaiting_approval','rollback_awaiting_approval'].includes(item.status))out+=` <button class="btn-danger" data-cancel="${Number(item.id)}">Cancel</button>`;return out;}
async function syncActive(items){const active=items.filter(item=>['backup_running','approved','running','rolling_back'].includes(item.status));if(active.length)await Promise.all(active.map(item=>post('sync',item.id).catch(()=>null)));}
async function loadJobs(){const data=await request(`${api}?action=list&page=${page}&per_page=25`),p=data.pagination;page=p.page;summary.textContent=p.total?`Showing ${p.from}-${p.to} of ${p.total} database restore gate(s)`:'No database restore gates yet';document.getElementById('prev').disabled=!p.has_previous;document.getElementById('next').disabled=!p.has_next;await syncActive(data.jobs||[]);if(!data.jobs.length){jobs.innerHTML='<tr><td colspan="9" class="empty">No database restore gates yet.</td></tr>';return;}jobs.innerHTML=data.jobs.map(item=>`<tr><td>#${Number(item.id)}</td><td><span class="status ${esc(item.status)}">${esc(item.status)}</span><div class="small">${esc(item.last_error||'')}</div></td><td>#${Number(item.preview_job_id)}<div class="small">${Number(item.preview_status?1:0)?esc(item.preview_status):''}</div></td><td>#${Number(item.pre_restore_backup_job_id||0)}<div class="small">${esc(item.pre_backup_status||'')}</div></td><td>${approvalText(item)}</td><td>${Number(item.target_table_count||0)} / ${Number(item.expected_table_count||0)}</td><td>${Number(item.pdf_missing_count||0)} missing · ${Number(item.pdf_invalid_count||0)} invalid</td><td>${esc(item.created_at||'')}</td><td>${actions(item)}</td></tr>`).join('');jobs.querySelectorAll('[data-detail]').forEach(button=>button.addEventListener('click',()=>showDetail(Number(button.dataset.detail)).catch(error=>alert(error.message))));jobs.querySelectorAll('[data-sync]').forEach(button=>button.addEventListener('click',()=>post('sync',Number(button.dataset.sync)).then(loadJobs).catch(error=>alert(error.message))));jobs.querySelectorAll('[data-approve]').forEach(button=>button.addEventListener('click',()=>approve(Number(button.dataset.id),button.dataset.approve,Number(button.dataset.stage)).catch(error=>alert(error.message))));jobs.querySelectorAll('[data-cancel]').forEach(button=>button.addEventListener('click',()=>cancelJob(Number(button.dataset.cancel)).catch(error=>alert(error.message))));}
async function post(action,id,extra={}){const form=new FormData();form.append('action',action);if(id)form.append('job_id',id);form.append('csrf_token',csrf);Object.entries(extra).forEach(([key,value])=>form.append(key,value));return request(api,{method:'POST',body:form});}
async function showDetail(id){const data=await request(`${api}?action=job&job_id=${id}`);document.getElementById('detail').hidden=false;document.getElementById('detail-title').textContent=`Database restore gate #${id} — ${data.job.status}`;document.getElementById('detail-summary').textContent=`Preview #${data.job.preview_job_id} | pre-restore backup #${data.job.pre_restore_backup_job_id||'-'} | approvals: ${(data.approvals||[]).map(item=>`${item.action} Stage ${item.stage}: ${item.full_name||item.username||item.user_id}`).join(' · ')||'none'}`;document.getElementById('logs').textContent=(data.logs||[]).reverse().map(item=>`[${item.created_at}] ${String(item.level).toUpperCase()}: ${item.message}`).join('\n')||'No logs yet.';}
async function approve(id,operation,stage){if(!maintenance){alert('Enable Maintenance Mode first.');return;}const label=operation==='rollback'?'rollback':'full database restore';if(!confirm(`Record ${label} approval Stage ${stage} for gate #${id}? This may lead to a live database replacement.`))return;await post('approve',id,{operation,stage});await loadJobs();alert(`Approval Stage ${stage} recorded.`);}
async function cancelJob(id){if(!confirm(`Cancel database restore gate #${id}? Existing backups remain available.`))return;await post('cancel',id);await loadJobs();}
document.getElementById('form').addEventListener('submit',async event=>{event.preventDefault();const button=document.getElementById('start');button.disabled=true;const form=new FormData();form.append('action','create');form.append('preview_job_id',preview.value);form.append('storage_root',root.value);form.append('folder_name',document.getElementById('folder').value);form.append('csrf_token',csrf);try{const data=await request(api,{method:'POST',body:form});alert(`${data.message} Gate ID: ${data.job_id}`);await loadJobs();}catch(error){alert(error.message);}finally{button.disabled=false;}});document.getElementById('prev').addEventListener('click',()=>{if(page>1){page--;loadJobs().catch(error=>alert(error.message));}});document.getElementById('next').addEventListener('click',()=>{page++;loadJobs().catch(error=>alert(error.message));});if(window.lucide)lucide.createIcons();Promise.all([loadSetup(),loadJobs()]).catch(error=>alert(error.message));setInterval(()=>loadSetup().then(loadJobs).catch(()=>{}),5000);
</script>
</body>
</html>
