<?php
require_once '../includes/session_config.php';require_once '../includes/config.php';require_once '../includes/functions.php';require_once '../includes/auth.php';require_once '../includes/security.php';requireAuth();requireAdmin();setSecurityHeaders();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?= csrfTokenMeta() ?><title>Database Backups - <?= htmlspecialchars(APP_SHORT_NAME) ?></title><?= google_fonts_tag('Inter:wght@400;500;600;700;800') ?><script src="<?= asset_url('lucide') ?>"></script><link rel="stylesheet" href="../assets/css/sidebar.css?v=20260929-groups"><style>
:root{--ink:#172033;--muted:#64748b;--line:#e2e8f0;--bg:#f6f8fb;--primary:#6750a4;--good:#15803d;--bad:#b91c1c}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,"Segoe UI",sans-serif}.content{padding:30px 36px;max-width:1700px}.hero{background:linear-gradient(135deg,#1e293b,#0f172a);color:#fff;border-radius:16px;padding:28px 32px;margin-bottom:20px}.hero h1{margin:0 0 7px;font-size:27px;display:flex;align-items:center;gap:10px}.hero p{margin:0;opacity:.9;font-size:14px}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 1px 3px #0000000d}.notice{padding:12px 14px;border-radius:9px;background:#eff6ff;border:1px solid #bfdbfe;color:#1e3a8a;font-size:13px;margin-bottom:16px}.form-grid{display:grid;grid-template-columns:1.2fr 1fr auto;gap:12px;align-items:end}.field label{display:block;font-size:12px;font-weight:800;color:#475569;margin-bottom:5px}.field input,.field select{width:100%;border:1px solid #cbd5e1;border-radius:8px;padding:10px;background:#fff;font:inherit;font-size:13px}.btn{border:0;border-radius:8px;padding:10px 15px;font:inherit;font-size:13px;font-weight:700;cursor:pointer}.btn-primary{background:var(--primary);color:#fff}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:10px}table{width:100%;border-collapse:collapse;min-width:1050px}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;font-size:12px}th{background:#f8fafc;color:#475569;font-size:11px;text-transform:uppercase}.status{display:inline-flex;padding:4px 8px;border-radius:999px;background:#eef2f7;font-weight:800}.status.completed{background:#ecfdf3;color:var(--good)}.status.running,.status.queued{background:#eff6ff;color:#1d4ed8}.status.failed,.status.completed_with_errors{background:#fef2f2;color:var(--bad)}.small{font-size:11px;color:var(--muted)}.path{max-width:430px;word-break:break-all}.pagination{display:flex;justify-content:space-between;align-items:center;margin-top:14px}.pagination button,td button{border:1px solid #cbd5e1;background:#fff;border-radius:7px;padding:7px 10px;cursor:pointer}.logs{max-height:240px;overflow:auto;background:#0f172a;color:#dbeafe;border-radius:9px;padding:12px;font:12px Consolas,monospace;white-space:pre-wrap}.empty{padding:28px;text-align:center;color:var(--muted)}@media(max-width:900px){.content{padding:20px}.form-grid{grid-template-columns:1fr}}
</style></head><body><?php require_once '../includes/sidebar_nav.php'; ?><main class="content"><section class="hero"><h1><i data-lucide="database-backup"></i> Full Database Backups</h1><p>Create verified MySQL dumps on an approved external location and monitor every backup job.</p></section><section class="card"><div class="notice"><strong>Safe backup:</strong> this creates a consistent read-only dump using a transaction snapshot. It does not change live records. A manifest with file size and SHA-256 is written beside the dump.</div><form id="form"><div class="form-grid"><div class="field"><label for="root">Storage drive / approved root</label><select id="root" required><option value="">Loading...</option></select></div><div class="field"><label for="folder">Backup folder name</label><input id="folder" maxlength="80" required value="iSCAN-DB-Backup_<?= date('Y-m-d') ?>"></div><button class="btn btn-primary" id="start" type="submit">Start database backup</button></div></form></section><section class="card"><div class="table-wrap"><table><thead><tr><th>ID</th><th>Status</th><th>Destination</th><th>Database</th><th>Size</th><th>SHA-256</th><th>Created</th><th>Actions</th></tr></thead><tbody id="jobs"><tr><td colspan="8" class="empty">Loading...</td></tr></tbody></table></div><div class="pagination"><span class="small" id="summary">Loading...</span><span><button id="prev" disabled>Previous</button> <button id="next" disabled>Next</button></span></div></section><section class="card" id="detail" hidden><h2 style="margin-top:0" id="detail-title">Backup details</h2><p class="small" id="detail-path"></p><div class="logs" id="logs"></div></section></main>
<script>
const api='../api/database_backup.php',verifyApi='../api/database_backup_verify.php',csrf=document.querySelector('meta[name="csrf-token"]')?.content||'',root=document.getElementById('root'),jobs=document.getElementById('jobs'),summary=document.getElementById('summary');let page=1;
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
async function request(url,options){const response=await fetch(url,{credentials:'same-origin',...(options||{})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'Database backup request failed.');return data;}
async function loadLocations(){const data=await request(`${api}?action=locations`);root.innerHTML=(data.locations||[]).map(item=>`<option value="${esc(item.root)}">${esc(item.root)} — ${Number(item.free_gb||0).toLocaleString()} GB free — ${item.writable?'writable':'read-only'}</option>`).join('')||'<option value="">No approved roots available</option>';}
function size(value){const n=Number(value||0);if(!n)return'-';if(n<1048576)return`${(n/1024).toFixed(1)} KB`;if(n<1073741824)return`${(n/1048576).toFixed(1)} MB`;return`${(n/1073741824).toFixed(2)} GB`;}
async function loadJobs(){const data=await request(`${api}?action=list&page=${page}&per_page=25`),p=data.pagination;page=p.page;summary.textContent=p.total?`Showing ${p.from}-${p.to} of ${p.total} backup job(s)`:'No database backups yet';document.getElementById('prev').disabled=!p.has_previous;document.getElementById('next').disabled=!p.has_next;if(!data.jobs.length){jobs.innerHTML='<tr><td colspan="8" class="empty">No database backup jobs yet.</td></tr>';return;}jobs.innerHTML=data.jobs.map(item=>`<tr><td>#${Number(item.id)}</td><td><span class="status ${esc(item.status)}">${esc(item.status)}</span><div class="small">${esc(item.last_error||'')}</div></td><td class="path">${esc(item.backup_folder)}</td><td>${esc(item.database_name)}<div class="small">${esc(item.database_host)}</div></td><td>${size(item.file_size)}</td><td style="max-width:220px;word-break:break-all">${esc(item.file_hash||'-')}</td><td>${esc(item.created_at||'')}</td><td><button data-detail="${Number(item.id)}">Details</button> <button data-verify="${Number(item.id)}">Verify</button></td></tr>`).join('');jobs.querySelectorAll('[data-detail]').forEach(button=>button.addEventListener('click',()=>showDetail(Number(button.dataset.detail))));jobs.querySelectorAll('[data-verify]').forEach(button=>button.addEventListener('click',()=>verify(Number(button.dataset.verify)).catch(error=>alert(error.message))));}
async function showDetail(id){const data=await request(`${api}?action=job&job_id=${id}`);document.getElementById('detail').hidden=false;document.getElementById('detail-title').textContent=`Database backup #${id} — ${data.job.status}`;document.getElementById('detail-path').textContent=`Dump: ${data.job.dump_path||'not completed'} | Manifest: ${data.job.manifest_path||'not completed'} | Manifest hash: ${data.job.manifest_hash||'-'}`;document.getElementById('logs').textContent=(data.logs||[]).reverse().map(item=>`[${item.created_at}] ${String(item.level).toUpperCase()}: ${item.message}`).join('\n')||'No logs yet.';}
async function verify(id){const data=await request(`${verifyApi}?job_id=${id}`),v=data.verification;alert(`Backup #${id}: ${v.valid?'VALID':'FAILED'}\nDump size: ${size(v.file_size)}\nCREATE TABLE statements: ${v.table_statements}\nINSERT statements: ${v.insert_statements}\nChecked: ${v.checked_at}`);}
document.getElementById('form').addEventListener('submit',async event=>{event.preventDefault();const button=document.getElementById('start');button.disabled=true;const form=new FormData();form.append('action','create');form.append('csrf_token',csrf);form.append('storage_root',root.value);form.append('folder_name',document.getElementById('folder').value);try{const data=await request(api,{method:'POST',body:form});alert(`${data.message} Job ID: ${data.job_id}`);await loadJobs();}catch(error){alert(error.message);}finally{button.disabled=false;}});
document.getElementById('prev').addEventListener('click',()=>{if(page>1){page--;loadJobs().catch(error=>alert(error.message));}});document.getElementById('next').addEventListener('click',()=>{page++;loadJobs().catch(error=>alert(error.message));});if(window.lucide)lucide.createIcons();Promise.all([loadLocations(),loadJobs()]).catch(error=>alert(error.message));setInterval(()=>loadJobs().catch(()=>{}),5000);
</script></body></html>
