<?php
/**
 * RA 9048 — Document Generator
 *
 * Auto-fills the office's .docx templates from a saved petition record and
 * writes the populated documents under uploads/ra9048/generated/petition_{id}/.
 *
 * Request (POST):
 *   petition_id   int           (required)
 *   doc_type      string        Optional. One of: petition, order_publication,
 *                                public_notice, cert_posting, cert_filing, all.
 *                                Defaults to 'all'.
 *
 * Response (JSON):
 *   {
 *     success: true,
 *     message: "...",
 *     data: {
 *       petition_id: 42,
 *       generated: [
 *         { doc_type: "petition", filename: "...", url: "...", template: "..." },
 *         ...
 *       ],
 *       skipped: [
 *         { doc_type: "order_publication", reason: "Subtype CCE_minor doesn't require publication." }
 *       ]
 *     }
 *   }
 *
 * Each output document is generated by:
 *   1. Loading the matching .docx template from documents/templates/
 *   2. Running it through DocxTemplateProcessor with the petition's data + child rows
 *   3. Saving the populated .docx under uploads/ra9048/generated/petition_{id}/
 *
 * Templates are expected to use ${placeholder} tokens. Phase 4b is the manual
 * step where the user opens each template in Word and replaces hardcoded
 * sample data with the placeholders listed in the cheat sheet.
 */

require_once '../../includes/config_ra9048.php';
require_once '../../includes/functions.php';
require_once '../../includes/auth.php';
require_once '../../includes/security.php';
require_once __DIR__ . '/../../includes/DocxTemplateProcessor.php';

header('Content-Type: application/json');

requireAuth();
requireCSRFToken();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    json_response(false, 'Invalid request method.', null, 405);
}

// ---- Constants ----------------------------------------------------------

const RA9048_GENERATED_SUBDIR = 'generated';

/**
 * Map doc_type → template filename + output filename pattern + applies-to logic.
 * Output filenames are intentionally simple, no spaces, ASCII only.
 */
function ra9048_doc_definitions(): array
{
    return [
        // Petition itself — chooses CFN or CCE template based on subtype.
        // Uses the ORIGINAL office templates that the user manually placeholder-edits
        // in Word (find/replace sample data with ${...} tokens). The system fills
        // those placeholders at generation time.
        'petition' => [
            'label'       => 'Petition',
            'output_stem' => 'petition',
            'template_for_subtype' => [
                'CCE_minor' => 'RA 9048 petition (birth) 2.docx',
                'CCE_10172' => 'RA 9048 petition (birth) 2.docx',
                'CFN'       => 'RA 9048 (CFN) 2.docx',
            ],
            'applies_to' => ['CCE_minor', 'CCE_10172', 'CFN'],
        ],
        'order_publication' => [
            'label'       => 'Order for Publication',
            'output_stem' => 'order_for_publication',
            'template'    => 'publication(CFN).docx',
            'applies_to'  => ['CCE_10172', 'CFN'],
        ],
        'public_notice' => [
            'label'       => 'Public Notice',
            'output_stem' => 'public_notice',
            'template'    => 'RA 10172 publication.pptx',
            'applies_to'  => ['CCE_10172', 'CFN'],
            'note'        => 'pptx — handled separately if/when needed; same placeholder approach.',
        ],
        'cert_posting' => [
            'label'       => 'Certificate of Posting',
            'output_stem' => 'cert_of_posting',
            'template'    => 'cert of posting.doc',
            'applies_to'  => ['CCE_minor', 'CCE_10172', 'CFN'],
        ],
        'cert_filing' => [
            'label'       => 'Certification of Proof of Filing',
            'output_stem' => 'certification_of_filing',
            'template'    => 'certification.doc',
            'applies_to'  => ['CCE_minor', 'CCE_10172', 'CFN'],
        ],
    ];
}

// ---- Inputs -------------------------------------------------------------

$petition_id = (int) ($_POST['petition_id'] ?? 0);
$doc_type    = sanitize_input($_POST['doc_type'] ?? 'all');

if ($petition_id <= 0) {
    json_response(false, 'petition_id is required.', null, 400);
}

$defs = ra9048_doc_definitions();
$validTypes = array_keys($defs);
if ($doc_type !== 'all' && !in_array($doc_type, $validTypes, true)) {
    json_response(false, 'Unknown doc_type.', null, 400);
}

// ---- Load petition + child rows -----------------------------------------

try {
    $stmt = $pdo_ra->prepare("SELECT * FROM petitions WHERE id = :id AND status = 'Active'");
    $stmt->execute([':id' => $petition_id]);
    $petition = $stmt->fetch();
    if (!$petition) {
        json_response(false, 'Petition not found.', null, 404);
    }

    $stmt = $pdo_ra->prepare(
        "SELECT * FROM petition_corrections WHERE petition_id = :id ORDER BY item_no ASC"
    );
    $stmt->execute([':id' => $petition_id]);
    $corrections = $stmt->fetchAll();

    $stmt = $pdo_ra->prepare(
        "SELECT * FROM petition_supporting_docs WHERE petition_id = :id ORDER BY item_no ASC"
    );
    $stmt->execute([':id' => $petition_id]);
    $supporting_docs = $stmt->fetchAll();

} catch (PDOException $e) {
    error_log('RA9048 generate_document load error: ' . $e->getMessage());
    json_response(false, 'Failed to load petition.', null, 500);
}

// ---- Build value bag (every placeholder a template might reference) -----

$values = ra9048_build_template_values($petition, $corrections, $supporting_docs);

// ---- Decide which doc_types to generate ---------------------------------

$subtype  = $petition['petition_subtype'] ?? '';
$toGenerate = ($doc_type === 'all') ? $validTypes : [$doc_type];

$outputDir = RA9048_UPLOAD_PATH . RA9048_GENERATED_SUBDIR . '/petition_' . $petition_id . '/';
if (!is_dir($outputDir) && !mkdir($outputDir, 0755, true) && !is_dir($outputDir)) {
    json_response(false, 'Failed to create output directory.', null, 500);
}

$generated = [];
$skipped   = [];

foreach ($toGenerate as $type) {
    $def = $defs[$type];

    if (!in_array($subtype, $def['applies_to'], true)) {
        $skipped[] = [
            'doc_type' => $type,
            'reason'   => "Subtype {$subtype} does not require {$def['label']}.",
        ];
        continue;
    }

    // Resolve the template path
    if (isset($def['template_for_subtype'])) {
        $tplName = $def['template_for_subtype'][$subtype] ?? null;
    } else {
        $tplName = $def['template'] ?? null;
    }
    if (!$tplName) {
        $skipped[] = ['doc_type' => $type, 'reason' => 'No template configured.'];
        continue;
    }

    $tplPath = RA9048_TEMPLATES_PATH . $tplName;
    if (!is_file($tplPath)) {
        $skipped[] = ['doc_type' => $type, 'reason' => "Template file missing: {$tplName}"];
        continue;
    }

    $ext = strtolower(pathinfo($tplName, PATHINFO_EXTENSION));

    // .doc and .pptx fallthrough — DocxTemplateProcessor only handles .docx.
    // For Phase 4a we still record the intent; Phase 4b can convert these
    // templates to .docx so the same engine processes them.
    if ($ext !== 'docx') {
        $skipped[] = [
            'doc_type' => $type,
            'reason'   => "Template format ({$ext}) not yet supported by the engine — convert {$tplName} to .docx in Phase 4b.",
        ];
        continue;
    }

    $outputName = $def['output_stem'] . '_' . $petition_id . '.docx';
    $outputPath = $outputDir . $outputName;

    try {
        $processor = new DocxTemplateProcessor($tplPath);
        $processor->setValues($values['scalar']);

        // Table-row clones for grids — only fire if the template has the marker.
        $processor->cloneRowAndSetValues('corrections_block',     $values['corrections_rows']);
        $processor->cloneRowAndSetValues('supporting_block',      $values['supporting_rows']);
        $processor->cloneRowAndSetValues('public_notice_block',   $values['public_notice_rows']);

        $processor->saveAs($outputPath);

        // Auto-convert .docx → .pdf via LibreOffice headless. The PDF lives next
        // to the .docx so the preview modal and "Download PDF" button can grab it.
        // If conversion fails (LibreOffice missing on the host, etc.), the .docx
        // is still usable — we just record pdf_url as null.
        $pdfName = $def['output_stem'] . '_' . $petition_id . '.pdf';
        $pdfPath = $outputDir . $pdfName;
        $pdfUrl  = null;
        $pdfError = ra9048_convert_to_pdf($outputPath, $outputDir);
        if ($pdfError === null && is_file($pdfPath)) {
            $pdfRelPath = 'ra9048/' . RA9048_GENERATED_SUBDIR . '/petition_' . $petition_id . '/' . $pdfName;
            $pdfUrl = rtrim(defined('BASE_URL') ? BASE_URL : '/iscan/', '/')
                    . '/api/serve_ra9048_doc.php?file=' . rawurlencode($pdfRelPath);
        } elseif ($pdfError !== null) {
            error_log("RA9048 PDF conversion failed for {$outputName}: {$pdfError}");
        }

        // URL is served via api/serve_ra9048_doc.php?file=...
        $relPath  = 'ra9048/' . RA9048_GENERATED_SUBDIR . '/petition_' . $petition_id . '/' . $outputName;
        $baseUrl  = rtrim(defined('BASE_URL') ? BASE_URL : '/iscan/', '/');
        $generated[] = [
            'doc_type' => $type,
            'label'    => $def['label'],
            'filename' => $outputName,
            'url'      => $baseUrl . '/api/serve_ra9048_doc.php?file=' . rawurlencode($relPath),
            'pdf_url'  => $pdfUrl,
            'template' => $tplName,
        ];
    } catch (Throwable $e) {
        error_log("RA9048 generate_document [{$type}] error: " . $e->getMessage());
        $skipped[] = [
            'doc_type' => $type,
            'reason'   => 'Generation failed: ' . $e->getMessage(),
        ];
    }
}

// ---- Activity log + response -------------------------------------------

if (!empty($generated)) {
    $labels = array_map(function ($g) { return $g['label']; }, $generated);
    log_activity(
        $pdo,
        'RA9048 Documents Generated',
        "Petition #{$petition_id} ({$petition['petition_number']}): " . implode(', ', $labels),
        $_SESSION['user_id'] ?? null
    );
}

$msgGen  = count($generated);
$msgSkip = count($skipped);
$message = $msgGen
    ? "Generated {$msgGen} document(s)" . ($msgSkip ? ", skipped {$msgSkip}." : '.')
    : ($msgSkip ? "No documents generated. {$msgSkip} skipped." : 'Nothing to do.');

json_response(true, $message, [
    'petition_id' => $petition_id,
    'generated'   => $generated,
    'skipped'     => $skipped,
]);


// =====================================================================
// Helpers (kept at the bottom so the request flow above reads top-down)
// =====================================================================

/**
 * Convert a .docx to .pdf via LibreOffice headless. Returns null on success,
 * or a short error string on failure. The PDF lands next to the source in
 * $outDir with the same stem (LibreOffice's default behavior).
 *
 * Uses LIBREOFFICE_PATH from .env. If the env var is missing or the binary
 * isn't found, returns "LibreOffice not configured" — caller treats that as a
 * soft skip so the .docx is still served.
 *
 * --user-installation forces a private profile dir per request, so concurrent
 * conversions don't fight over the same LibreOffice user profile (which is the
 * #1 cause of "LibreOffice already running" hangs in CGI/Apache contexts).
 */
function ra9048_convert_to_pdf(string $docxPath, string $outDir): ?string
{
    $soffice = trim((string) env('LIBREOFFICE_PATH', ''));
    if ($soffice === '') {
        return 'LibreOffice not configured (LIBREOFFICE_PATH missing).';
    }

    // Two modes:
    //   docker:<image-name>   → wrap soffice in `docker run`, mounting the docx's
    //                           parent dir at /data inside the container.
    //   <path-to-soffice>     → invoke the local binary directly.
    if (strncmp($soffice, 'docker:', 7) === 0) {
        return ra9048_convert_via_docker(substr($soffice, 7), $docxPath, $outDir);
    }

    if (!is_file($soffice)) {
        return 'LibreOffice not configured (binary not found at ' . $soffice . ').';
    }

    $profileDir = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'lo_profile_' . bin2hex(random_bytes(4));
    $profileUri = 'file:///' . str_replace('\\', '/', $profileDir);

    $cmd = escapeshellarg($soffice)
         . ' --headless'
         . ' --norestore'
         . ' --nolockcheck'
         . ' --nodefault'
         . ' --nofirststartwizard'
         . ' -env:UserInstallation=' . escapeshellarg($profileUri)
         . ' --convert-to pdf'
         . ' --outdir ' . escapeshellarg(rtrim($outDir, "/\\"))
         . ' ' . escapeshellarg($docxPath)
         . ' 2>&1';

    $output = [];
    $exitCode = 0;
    exec($cmd, $output, $exitCode);

    // Best-effort cleanup of the throwaway profile dir.
    if (is_dir($profileDir)) {
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($profileDir, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );
        foreach ($files as $f) {
            $f->isDir() ? @rmdir($f->getRealPath()) : @unlink($f->getRealPath());
        }
        @rmdir($profileDir);
    }

    if ($exitCode !== 0) {
        return 'soffice exit ' . $exitCode . ': ' . implode(' | ', $output);
    }
    return null;
}

/**
 * Convert a .docx via a containerized LibreOffice (Synology NAS path).
 *
 * Mounts the .docx's parent directory at /data inside the container so we can
 * pass container-internal paths to soffice. Both $docxPath and $outDir must
 * live under the same parent dir (which is true for our generator — the .docx
 * is saved to $outDir, and the .pdf is also written to $outDir).
 *
 * The image must have soffice as its ENTRYPOINT (e.g. our custom
 * iscan-libreoffice image built from a Debian + libreoffice + jre Dockerfile).
 *
 * Why `docker run --rm`: each call is one-shot, the throwaway container dies
 * after conversion. Adds ~1s overhead vs reusing a long-lived container, but
 * keeps deployment trivial — no daemon, no orchestration.
 */
function ra9048_convert_via_docker(string $image, string $docxPath, string $outDir): ?string
{
    $hostDir = realpath(dirname($docxPath));
    if ($hostDir === false) {
        return 'docker: source dir not found for ' . $docxPath;
    }
    $resolvedOutDir = realpath($outDir);
    if ($resolvedOutDir === false || strpos($resolvedOutDir, $hostDir) !== 0) {
        return 'docker: out dir must be inside source dir (got out=' . $outDir . ', src=' . $hostDir . ')';
    }

    // Translate host paths to container paths under /data.
    $containerDocx   = '/data/' . basename($docxPath);
    $relOut          = ltrim(substr($resolvedOutDir, strlen($hostDir)), DIRECTORY_SEPARATOR . '/');
    $containerOutDir = '/data' . ($relOut !== '' ? '/' . str_replace('\\', '/', $relOut) : '');

    $cmd = 'docker run --rm'
         . ' -v ' . escapeshellarg($hostDir . ':/data')
         . ' ' . escapeshellarg($image)
         . ' --convert-to pdf'
         . ' --outdir ' . escapeshellarg($containerOutDir)
         . ' ' . escapeshellarg($containerDocx)
         . ' 2>&1';

    $output = [];
    $exitCode = 0;
    exec($cmd, $output, $exitCode);

    if ($exitCode !== 0) {
        return 'docker exit ' . $exitCode . ': ' . implode(' | ', $output);
    }
    return null;
}

/**
 * Build the placeholder bag for the template processor. Returns:
 *   [
 *     'scalar'             => [ 'name' => 'value', ... ],
 *     'corrections_rows'   => [ ['item_no' => 1, 'description' => ...], ... ],
 *     'supporting_rows'    => [ ['item_no' => 1, 'doc_label' => ...], ... ],
 *     'public_notice_rows' => [ ['nature_label' => 'CHANGE OF FIRST NAME', 'value_from' => ...], ... ],
 *   ]
 *
 * Naming convention for placeholders matches the cheat sheet given to the user
 * for Phase 4b. Keys are snake_case ASCII only.
 */
function ra9048_build_template_values(array $petition, array $corrections, array $supporting_docs): array
{
    $cite = ra9048_citation((string) ($petition['petition_subtype'] ?? ''));

    $scalar = [
        // Office constants
        'office_name'         => LCRO_OFFICE_NAME,
        'office_municipality' => LCRO_OFFICE_MUNICIPALITY,
        'office_province'     => LCRO_OFFICE_PROVINCE,
        'office_address'      => LCRO_OFFICE_ADDRESS,
        'office_email'        => LCRO_OFFICE_EMAIL,
        'mcr_full_name'       => LCRO_MCR_FULL_NAME,
        'mcr_title'           => LCRO_MCR_TITLE,

        // Citation
        'law'                 => $cite['law'],
        'irr'                 => $cite['irr'],
        'mc'                  => $cite['mc'] ?? '',
        'nature_label'        => $cite['nature_label'],

        // Petition
        'petition_number'     => $petition['petition_number'] ?? '',
        'petition_subtype'    => $petition['petition_subtype'] ?? '',
        'petition_type'       => $petition['petition_type'] ?? '',
        'date_of_filing'      => ra9048_fmt_date($petition['date_of_filing'] ?? ''),
        'fee_amount'          => ra9048_fmt_money($petition['fee_amount'] ?? 0),
        'document_type'       => ra9048_doc_type_label($petition['document_type'] ?? ''),
        'document_type_code'  => $petition['document_type'] ?? '',
        'petition_of'         => $petition['petition_of'] ?? '',
        'remarks'             => $petition['remarks'] ?? '',

        // Petitioner
        'petitioner_names'        => $petition['petitioner_names'] ?? '',
        'petitioner_nationality'  => $petition['petitioner_nationality'] ?? '',
        'petitioner_address'      => $petition['petitioner_address'] ?? '',
        'petitioner_id_type'      => $petition['petitioner_id_type'] ?? '',
        'petitioner_id_number'    => $petition['petitioner_id_number'] ?? '',
        'is_self_petition_label'  => !empty($petition['is_self_petition']) ? 'self' : 'other',
        'relation_to_owner'       => $petition['relation_to_owner'] ?? '',

        // Document owner
        'document_owner_names'    => $petition['document_owner_names'] ?? '',
        'owner_dob'               => ra9048_fmt_date($petition['owner_dob'] ?? ''),
        'owner_birthplace_city'   => $petition['owner_birthplace_city'] ?? '',
        'owner_birthplace_province'=> $petition['owner_birthplace_province'] ?? '',
        'owner_birthplace_country' => $petition['owner_birthplace_country'] ?? '',
        'registry_number'         => $petition['registry_number'] ?? '',
        'father_full_name'        => $petition['father_full_name'] ?? '',
        'mother_full_name'        => $petition['mother_full_name'] ?? '',

        // CFN
        'cfn_ground'              => ra9048_cfn_ground_label($petition['cfn_ground'] ?? ''),
        'cfn_ground_detail'       => $petition['cfn_ground_detail'] ?? '',

        // Notarization & payment
        'notarized_at'            => ra9048_fmt_date($petition['notarized_at'] ?? ''),
        'notarized_day'           => ra9048_fmt_day_th($petition['notarized_at'] ?? ''),
        'notarized_month_year'    => ra9048_fmt_month_year($petition['notarized_at'] ?? ''),
        'receipt_number'          => $petition['receipt_number'] ?? '',
        'payment_date'            => ra9048_fmt_date($petition['payment_date'] ?? ''),

        // Posting
        'posting_start_date'      => ra9048_fmt_date($petition['posting_start_date'] ?? ''),
        'posting_end_date'        => ra9048_fmt_date($petition['posting_end_date'] ?? ''),
        'posting_location'        => $petition['posting_location'] ?? '',
        'posting_cert_issued_at'  => ra9048_fmt_date($petition['posting_cert_issued_at'] ?? '') ?: ra9048_fmt_date(date('Y-m-d')),

        // Publication
        'order_date'              => ra9048_fmt_date($petition['order_date'] ?? ''),
        'order_day'               => ra9048_fmt_day_th($petition['order_date'] ?? ''),
        'order_month_year'        => ra9048_fmt_month_year($petition['order_date'] ?? ''),
        'publication_date_1'      => ra9048_fmt_date($petition['publication_date_1'] ?? ''),
        'publication_date_2'      => ra9048_fmt_date($petition['publication_date_2'] ?? ''),
        'publication_dates_combined' => trim(
            ra9048_fmt_date($petition['publication_date_1'] ?? '')
            . (!empty($petition['publication_date_2']) ? ' & ' . ra9048_fmt_date($petition['publication_date_2']) : '')
        ),
        'publication_newspaper'   => $petition['publication_newspaper'] ?? '',
        'publication_place'       => $petition['publication_place'] ?? '',
        'opposition_deadline'     => ra9048_fmt_date($petition['opposition_deadline'] ?? ''),

        // Issuance dates (used on the various certifications)
        'today_date'              => ra9048_fmt_date(date('Y-m-d')),
        'today_day'               => ra9048_fmt_day_th(date('Y-m-d')),
        'today_month_year'        => ra9048_fmt_month_year(date('Y-m-d')),
        'certification_issued_at' => ra9048_fmt_date($petition['certification_issued_at'] ?? '') ?: ra9048_fmt_date(date('Y-m-d')),
    ];

    // Build correction rows (used by the Petition + Certification + Public Notice templates)
    $corr_rows = [];
    foreach ($corrections as $i => $c) {
        $corr_rows[] = [
            'item_no'       => $i + 1,
            'nature'        => $c['nature'] ?? 'CCE',
            'nature_label'  => ($c['nature'] === 'CFN') ? 'CHANGE OF FIRST NAME' : 'CORRECTION OF CLERICAL ERROR',
            'description'   => $c['description'] ?? '',
            'value_from'    => $c['value_from'] ?? '',
            'value_to'      => $c['value_to'] ?? '',
        ];
    }

    // Expose the FIRST correction's fields as inline scalars for templates that
    // reference the FROM/TO outside a table (e.g. the Order for Publication body
    // text "from X to Y"). When there are no corrections, these fall back to '-.-'.
    $first = $corr_rows[0] ?? null;
    $scalar['first_description']  = $first['description']  ?? '';
    $scalar['first_value_from']   = $first['value_from']   ?? '';
    $scalar['first_value_to']     = $first['value_to']     ?? '';
    $scalar['first_nature_label'] = $first['nature_label'] ?? '';

    $supp_rows = [];
    foreach ($supporting_docs as $i => $d) {
        $supp_rows[] = [
            'item_no'   => $i + 1,
            'doc_label' => $d['doc_label'] ?? '',
        ];
    }

    // Public Notice grid expects one CFN summary row + one CCE summary row.
    // Pull the first CFN-nature correction and the first CCE-nature correction.
    $cfn_match = null;
    $cce_match = null;
    foreach ($corr_rows as $r) {
        if ($r['nature'] === 'CFN' && !$cfn_match) $cfn_match = $r;
        if ($r['nature'] === 'CCE' && !$cce_match) $cce_match = $r;
    }
    $public_notice_rows = [
        [
            'nature_label' => 'CHANGE OF FIRST NAME',
            'value_from'   => $cfn_match['value_from'] ?? '-.-',
            'value_to'     => $cfn_match['value_to']   ?? '-.-',
        ],
        [
            'nature_label' => 'CORRECTION OF CLERICAL ERROR',
            'value_from'   => $cce_match['value_from'] ?? '-.-',
            'value_to'     => $cce_match['value_to']   ?? '-.-',
        ],
    ];

    return [
        'scalar'             => $scalar,
        'corrections_rows'   => $corr_rows,
        'supporting_rows'    => $supp_rows,
        'public_notice_rows' => $public_notice_rows,
    ];
}

function ra9048_fmt_date(?string $iso): string
{
    if (!$iso) return '';
    $ts = strtotime($iso);
    if ($ts === false) return '';
    return strtoupper(date('F j, Y', $ts));
}

function ra9048_fmt_day_th(?string $iso): string
{
    if (!$iso) return '';
    $ts = strtotime($iso);
    if ($ts === false) return '';
    $d = (int) date('j', $ts);
    $suffix = 'th';
    if (!in_array($d % 100, [11, 12, 13], true)) {
        switch ($d % 10) {
            case 1: $suffix = 'st'; break;
            case 2: $suffix = 'nd'; break;
            case 3: $suffix = 'rd'; break;
        }
    }
    return $d . $suffix;
}

function ra9048_fmt_month_year(?string $iso): string
{
    if (!$iso) return '';
    $ts = strtotime($iso);
    if ($ts === false) return '';
    return strtoupper(date('F, Y', $ts));
}

function ra9048_fmt_money($v): string
{
    $f = (float) $v;
    return number_format($f, 2);
}

function ra9048_doc_type_label(string $code): string
{
    $map = [
        'COLB' => 'CERTIFICATE OF LIVE BIRTH',
        'COM'  => 'CERTIFICATE OF MARRIAGE',
        'COD'  => 'CERTIFICATE OF DEATH',
    ];
    return $map[$code] ?? $code;
}

function ra9048_cfn_ground_label(string $code): string
{
    $map = [
        'difficult' => 'The first name is extremely difficult to write or pronounce',
        'habitual'  => 'I/He/She has habitually and continuously used another name',
        'ridicule'  => 'The first name is the subject of ridicule',
        'confusion' => 'The first name causes confusion',
    ];
    return $map[$code] ?? '';
}
