<?php
/** Full database replacement restore and rollback gate API. */
require_once '../includes/session_config.php';require_once '../includes/config.php';require_once '../includes/functions.php';require_once '../includes/auth.php';require_once '../includes/security.php';require_once '../includes/settings.php';require_once '../includes/pdf_backup_locations.php';require_once '../includes/database_backup_launcher.php';require_once '../includes/database_live_restore_launcher.php';require_once '../includes/database_live_restore.php';
header('Content-Type: application/json; charset=utf-8');
if(!isLoggedIn()){http_response_code(401);echo json_encode(['success'=>false,'message'=>'Not authenticated']);exit;}if(getUserRole()!=='Admin'){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Admin access required']);exit;}$requestMethod=$_SERVER['REQUEST_METHOD']??'GET';$action=strtolower(trim((string)($_GET['action']??$_POST['action']??'list')));
try{
    if($action==='locations'&&$requestMethod==='GET'){$locations=[];foreach(pdf_backup_allowed_roots() as $root){try{$locations[]=pdf_backup_storage_info($root,false);}catch(Throwable $e){}}echo json_encode(['success'=>true,'locations'=>$locations,'maintenance_mode'=>database_live_restore_maintenance_enabled()]);exit;}
    if($action==='eligible'&&$requestMethod==='GET'){$stmt=$pdo->query("SELECT p.id,p.backup_job_id,p.status,b.database_name,p.staging_table_count,p.table_statements,p.pdf_reference_count,p.pdf_present_count,p.pdf_missing_count,p.pdf_invalid_count,p.created_at,b.status AS backup_status,b.dump_path,b.manifest_path FROM database_restore_preview_jobs p JOIN database_backup_jobs b ON b.id=p.backup_job_id WHERE p.status IN ('completed','completed_with_errors','cleaned') AND p.staging_table_count>0 AND p.table_statements>0 AND NOT EXISTS (SELECT 1 FROM database_live_restore_jobs l WHERE l.preview_job_id=p.id AND l.status NOT IN ('cancelled','failed','completed','completed_with_errors','rolled_back')) ORDER BY p.id DESC");echo json_encode(['success'=>true,'jobs'=>$stmt->fetchAll(PDO::FETCH_ASSOC),'maintenance_mode'=>database_live_restore_maintenance_enabled()]);exit;}
    if($action==='list'&&$requestMethod==='GET'){$page=max(1,(int)($_GET['page']??1));$perPage=(int)($_GET['per_page']??25);if(!in_array($perPage,[10,25,50,100],true))$perPage=25;$total=(int)$pdo->query('SELECT COUNT(*) FROM database_live_restore_jobs')->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));if($page>$pages)$page=$pages;$offset=($page-1)*$perPage;$stmt=$pdo->prepare('SELECT l.*,p.status AS preview_status,p.backup_job_id,p.pdf_reference_count,p.pdf_missing_count,p.pdf_invalid_count,b.status AS pre_backup_status,b.backup_folder AS pre_backup_folder,(SELECT COUNT(*) FROM database_live_restore_approvals a WHERE a.job_id=l.id AND a.action="restore" AND a.stage=1) AS restore_stage1_count,(SELECT COUNT(*) FROM database_live_restore_approvals a WHERE a.job_id=l.id AND a.action="restore" AND a.stage=2) AS restore_stage2_count,(SELECT COUNT(*) FROM database_live_restore_approvals a WHERE a.job_id=l.id AND a.action="rollback" AND a.stage=1) AS rollback_stage1_count,(SELECT COUNT(*) FROM database_live_restore_approvals a WHERE a.job_id=l.id AND a.action="rollback" AND a.stage=2) AS rollback_stage2_count FROM database_live_restore_jobs l JOIN database_restore_preview_jobs p ON p.id=l.preview_job_id LEFT JOIN database_backup_jobs b ON b.id=l.pre_restore_backup_job_id ORDER BY l.id DESC LIMIT :limit OFFSET :offset');$stmt->bindValue(':limit',$perPage,PDO::PARAM_INT);$stmt->bindValue(':offset',$offset,PDO::PARAM_INT);$stmt->execute();echo json_encode(['success'=>true,'jobs'=>$stmt->fetchAll(PDO::FETCH_ASSOC),'maintenance_mode'=>database_live_restore_maintenance_enabled(),'pagination'=>['page'=>$page,'per_page'=>$perPage,'total'=>$total,'total_pages'=>$pages,'from'=>$total?$offset+1:0,'to'=>min($offset+$perPage,$total),'has_previous'=>$page>1,'has_next'=>$page<$pages]]);exit;}
    $jobId=(int)($_GET['job_id']??$_POST['job_id']??0);if($action==='job'&&$jobId>0&&$requestMethod==='GET'){$job=get_database_live_restore_job($pdo,$jobId);if(!$job){http_response_code(404);echo json_encode(['success'=>false,'message'=>'Live database restore job not found.']);exit;}echo json_encode(['success'=>true,'job'=>$job,'approvals'=>database_live_restore_approvals($pdo,$jobId),'logs'=>database_live_restore_logs($pdo,$jobId)]);exit;}
    if($requestMethod!=='POST'){http_response_code(405);echo json_encode(['success'=>false,'message'=>'POST required.']);exit;}requireCSRFToken();$userId=(int)($_SESSION['user_id']??0);
    if($action==='create'){$previewJobId=(int)($_POST['preview_job_id']??0);$root=pdf_backup_find_allowed_root((string)($_POST['storage_root']??''));if($root===null)throw new InvalidArgumentException('Choose an approved storage root.');$folderName=pdf_backup_validate_folder_name((string)($_POST['folder_name']??''));$folder=pdf_backup_resolve_folder($root,$folderName,true,true);$newId=create_database_live_restore_job($pdo,$previewJobId,$root,$folder['path'],$userId);try{$newJob=get_database_live_restore_job($pdo,$newId);launch_database_backup_worker((int)$newJob['pre_restore_backup_job_id']);}catch(Throwable $e){update_database_live_restore_job($pdo,$newId,'failed',['last_error'=>$e->getMessage()]);database_live_restore_log($pdo,$newId,'error','Pre-restore backup could not start: '.$e->getMessage());throw$e;}if(function_exists('log_activity'))log_activity($pdo,'DATABASE_LIVE_RESTORE_PREPARED',sprintf('Live database restore gate %d prepared from preview job %d',$newId,$previewJobId),$userId?:null);echo json_encode(['success'=>true,'job_id'=>$newId,'message'=>'Pre-restore database backup started. Two administrator approvals will be required after verification.']);exit;}
    if($action==='sync'){if($jobId<=0)throw new InvalidArgumentException('A valid live database restore job is required.');echo json_encode(['success'=>true,'job'=>database_live_restore_sync_job($pdo,$jobId)]);exit;}
    if($action==='approve'){if($jobId<=0)throw new InvalidArgumentException('A valid live database restore job is required.');$operation=strtolower(trim((string)($_POST['operation']??'restore')));$stage=(int)($_POST['stage']??0);$result=database_live_restore_approve($pdo,$jobId,$operation,$stage,$userId);if(function_exists('log_activity'))log_activity($pdo,'DATABASE_LIVE_RESTORE_APPROVAL',sprintf('Live database %s gate %d approval stage %d recorded',$operation,$jobId,$stage),$userId?:null);echo json_encode(['success'=>true,'job'=>$result['job'],'message'=>$result['message']]);exit;}
    if($action==='cancel'){if($jobId<=0)throw new InvalidArgumentException('A valid live database restore job is required.');$job=database_live_restore_cancel($pdo,$jobId,$userId);if(function_exists('log_activity'))log_activity($pdo,'DATABASE_LIVE_RESTORE_CANCELLED',sprintf('Live database restore gate %d cancelled',$jobId),$userId?:null);echo json_encode(['success'=>true,'job'=>$job,'message'=>'Live database restore plan cancelled.']);exit;}
    http_response_code(400);echo json_encode(['success'=>false,'message'=>'Unsupported live database restore action.']);
}catch(Throwable $e){http_response_code(409);echo json_encode(['success'=>false,'message'=>$e->getMessage()]);}
