<?php
/** Controlled production PDF restore gate API. */
require_once '../includes/session_config.php';require_once '../includes/config.php';require_once '../includes/functions.php';require_once '../includes/auth.php';require_once '../includes/security.php';require_once '../includes/pdf_backup_locations.php';require_once '../includes/database_backup_launcher.php';require_once '../includes/production_restore_control.php';
header('Content-Type: application/json; charset=utf-8');
if(!isLoggedIn()){http_response_code(401);echo json_encode(['success'=>false,'message'=>'Not authenticated']);exit;}if(getUserRole()!=='Admin'){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Admin access required']);exit;}$action=strtolower(trim((string)($_GET['action']??$_POST['action']??'list')));
try{
    if($action==='locations'&&($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$locations=[];foreach(pdf_backup_allowed_roots() as $root){try{$locations[]=pdf_backup_storage_info($root,false);}catch(Throwable $e){}}echo json_encode(['success'=>true,'locations'=>$locations,'maintenance_mode'=>production_restore_maintenance_is_enabled()]);exit;}
    if($action==='eligible'&&($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$stmt=$pdo->query("SELECT r.id,r.status,r.source_root,r.destination_root,r.total_items,r.scanned_items,r.copied_items,r.skipped_items,r.failed_items,r.review_items,r.created_at FROM pdf_protection_jobs r LEFT JOIN production_restore_jobs p ON p.recovery_job_id=r.id WHERE r.job_type='recovery' AND r.status='preview_ready' AND r.total_items>0 AND r.scanned_items>=r.total_items AND r.failed_items=0 AND r.review_items=0 AND p.id IS NULL ORDER BY r.id DESC");echo json_encode(['success'=>true,'jobs'=>$stmt->fetchAll(PDO::FETCH_ASSOC)]);exit;}
    if($action==='list'&&($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$page=max(1,(int)($_GET['page']??1));$perPage=(int)($_GET['per_page']??25);if(!in_array($perPage,[10,25,50,100],true))$perPage=25;$total=(int)$pdo->query('SELECT COUNT(*) FROM production_restore_jobs')->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));if($page>$pages)$page=$pages;$offset=($page-1)*$perPage;$stmt=$pdo->prepare('SELECT p.*,r.status AS recovery_status,r.total_items AS recovery_total_items,r.scanned_items AS recovery_scanned_items,r.copied_items AS recovery_copied_items,r.skipped_items AS recovery_skipped_items,r.failed_items AS recovery_failed_items,r.review_items AS recovery_review_items,b.status AS pre_backup_status,b.backup_folder AS pre_backup_folder,(SELECT COUNT(*) FROM production_restore_approvals a WHERE a.job_id=p.id AND a.stage=1) AS first_approval_count,(SELECT COUNT(*) FROM production_restore_approvals a WHERE a.job_id=p.id AND a.stage=2) AS second_approval_count FROM production_restore_jobs p JOIN pdf_protection_jobs r ON r.id=p.recovery_job_id LEFT JOIN database_backup_jobs b ON b.id=p.pre_restore_backup_job_id ORDER BY p.id DESC LIMIT :limit OFFSET :offset');$stmt->bindValue(':limit',$perPage,PDO::PARAM_INT);$stmt->bindValue(':offset',$offset,PDO::PARAM_INT);$stmt->execute();echo json_encode(['success'=>true,'jobs'=>$stmt->fetchAll(PDO::FETCH_ASSOC),'maintenance_mode'=>production_restore_maintenance_is_enabled(),'pagination'=>['page'=>$page,'per_page'=>$perPage,'total'=>$total,'total_pages'=>$pages,'from'=>$total?$offset+1:0,'to'=>min($offset+$perPage,$total),'has_previous'=>$page>1,'has_next'=>$page<$pages]]);exit;}
    $jobId=(int)($_GET['job_id']??$_POST['job_id']??0);
    if($action==='job'&&$jobId>0&&($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$job=get_production_restore_job($pdo,$jobId);if(!$job){http_response_code(404);echo json_encode(['success'=>false,'message'=>'Production restore job not found.']);exit;}echo json_encode(['success'=>true,'job'=>$job,'approvals'=>production_restore_approvals($pdo,$jobId),'logs'=>production_restore_logs($pdo,$jobId)]);exit;}
    if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST'){http_response_code(405);echo json_encode(['success'=>false,'message'=>'POST required.']);exit;}requireCSRFToken();
    if($action==='create'){$recoveryJobId=(int)($_POST['recovery_job_id']??0);$root=pdf_backup_find_allowed_root((string)($_POST['storage_root']??''));if($root===null)throw new InvalidArgumentException('Choose an approved storage root.');$folderName=pdf_backup_validate_folder_name((string)($_POST['folder_name']??''));$folder=pdf_backup_resolve_folder($root,$folderName,true,true);$newId=create_production_restore_job($pdo,$recoveryJobId,$root,$folder['path'],(int)($_SESSION['user_id']??0));try{$newJob=get_production_restore_job($pdo,$newId);launch_database_backup_worker((int)$newJob['pre_restore_backup_job_id']);}catch(Throwable $e){update_production_restore_job($pdo,$newId,'failed',['last_error'=>$e->getMessage()]);production_restore_log($pdo,$newId,'error','Pre-restore backup could not start: '.$e->getMessage());throw $e;}if(function_exists('log_activity'))log_activity($pdo,'PRODUCTION_RESTORE_PREPARED',sprintf('Production restore gate %d prepared from recovery job %d',$newId,$recoveryJobId),$_SESSION['user_id']??null);echo json_encode(['success'=>true,'job_id'=>$newId,'message'=>'Pre-restore database backup started. Two approvals will be required after verification.']);exit;}
    if($action==='sync'){if($jobId<=0)throw new InvalidArgumentException('A valid production restore job is required.');echo json_encode(['success'=>true,'job'=>production_restore_sync_job($pdo,$jobId)]);exit;}
    if($action==='approve'){if($jobId<=0)throw new InvalidArgumentException('A valid production restore job is required.');$result=production_restore_approve($pdo,$jobId,(int)($_POST['stage']??0),(int)($_SESSION['user_id']??0));if(function_exists('log_activity'))log_activity($pdo,'PRODUCTION_RESTORE_APPROVAL',sprintf('Production restore gate %d approval stage %d recorded',$jobId,(int)($_POST['stage']??0)),$_SESSION['user_id']??null);echo json_encode(['success'=>true,'job'=>$result['job'],'message'=>$result['message']]);exit;}
    if($action==='cancel'){if($jobId<=0)throw new InvalidArgumentException('A valid production restore job is required.');$job=production_restore_cancel($pdo,$jobId,(int)($_SESSION['user_id']??0));if(function_exists('log_activity'))log_activity($pdo,'PRODUCTION_RESTORE_CANCELLED',sprintf('Production restore gate %d cancelled',$jobId),$_SESSION['user_id']??null);echo json_encode(['success'=>true,'job'=>$job,'message'=>'Production restore gate cancelled.']);exit;}
    http_response_code(400);echo json_encode(['success'=>false,'message'=>'Unsupported production restore action.']);
}catch(Throwable $e){http_response_code(409);echo json_encode(['success'=>false,'message'=>$e->getMessage()]);}
